### ISSUE TITLE
How does openocd search and select the developed cmsis-dap download program

### ISSUE THREAD

**Issue by ouki-wang** [arduino/OpenOCD#6]
Several cmsis-dap devices are linked on my computer. How does openocd search and select the cmsis-dap download program?

**Comment by facchinm** [comment]
In fact, openocd doesn't. It depends on the commandline you give it; the default one we use doesn't specify any serial number, so if you connect two programmers with the same vid and pid it fails. You can specify the serialnumber of the programmer you want to target with ` cmsis_dap_serial [serial]` (see http://openocd.org/doc/html/Debug-Adapter-Configuration.html)
